library(openxlsx) 
library(EnhancedVolcano)
library(Seurat)
library(SeuratObject)
library(writexl)
getwd()
# Introduce the interested genes into array
geneArray <- c("IL21","IL23A","CCR9","RORC","CD40LG","ITGA4","BCL6","ICOS","IL7R","MAF","RORA-AS2","IL17D","VDR","IL17A","IL17B","ITGB7","MAF1","IL17C","CCR6","RORA","IRF4")
# geneArray <- toupper(geneArray) # Capitalize if needed

# Import the difference matrix data generated by the 'Findmakrers'
data1 <- read.csv("123456_RA_VS_HC.csv")

# Subset data based on conditions, in this case p value < 0.05 and log2FC = 0.3219
up <- subset(data1, p_val_adj < 0.05 & avg_log2FC > 0.3219)
down <- subset(data1, p_val_adj < 0.05 & avg_log2FC < (-0.3219))

# Subset data based on gene array 
sampleGene <- data1[toupper(data1$X) %in% geneArray,] # In this case, sampleGene contains the genes that match the geneArray

# Select the genes that will be labeled on the volcano plot
label_up <- subset(sampleGene, avg_log2FC > 0.3219 & p_val_adj< 0.05)


# Optional: Save the information of the label genes of data for referencec
write_xlsx(label_up, paste0("up_ ", "RA_vs_HC_sample_genes.xlsx"))


# Print how many matched genes are counted in the up/down stream in the data
cat("Number of up-regulated genes: ", length(label_up$X), "\n")


# Create the basic volcano plot
p2 <- ggplot(data = data1, aes(x = avg_log2FC, y = -log10(p_val_adj))) +
  geom_point(size = 2, colour = "grey") + 
  geom_point(data = down, size = 2, colour = "#66B2FF") +
  geom_point(data = up, size = 2, colour = "#FF6666") +
  geom_point(data = label_up, shape = 21, colour = "black", fill = "#FFFF99", size = 4, stroke = 1) + # High light the selected genes
  geom_vline(xintercept = c(-0.3219, 0.3219), col = "blue", linetype = 'dashed') +
  geom_hline(yintercept = -log10(0.05), col = "black", linetype = 'dashed') +
  #annotate("text", x = 6, y = 25,label = paste("Number of up-regulated genes: ", length(label_up$X), "\n"), color = "blue")+
  #annotate("text", x = -6, y = 25,label = paste("Number of down-regulated genes: ", length(label_down$X), "\n"), color = "firebrick")+
  scale_x_continuous(breaks = seq(-4, 4, 2)) +
  coord_cartesian(xlim = c(-4, 4), ylim = c(0, 200)) +
  theme_bw()+
  theme(
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size = 30),
  )+
  xlab(NULL) +   # Remove x-axis label
  ylab(NULL)     # Remove y-axis label
print(p2)



# Add labels to the plot
options(ggrepel.max.overlaps = 20) # Set up  the potentially allowed overlaps
text_label_up <- label_up[toupper(label_up$X) %in% geneArray,]

# Print the final plot
p3 <- p2 +
  geom_label_repel(
    size = 15,
    xlim = c(-5, 5),
    ylim = c(25,200),
    data = text_label_up,
    aes(label = X), 
    nudge_x = .15,
    box.padding = 5,
    nudge_y = 1,
    arrow = arrow(length = unit(0.02, "npc"), type = "closed", ends = "last", angle = 15),
    segment.size = 1,
    force = 10  
  ) 
print(p3)



# Save the plot as PDF
pdf(paste("HC vs RA p_val_adj.pdf", sep = ""),width = 11, height = 12.5)
p3
dev.off()